### ISSUE TITLE
Go linting ignoring any rule breaches in /internal/pkg/*

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#352]
```yaml
    - path: internal/pkg/*
      linters:
        - revive
 ```

Currently, the following exclusion is present in the `.golangci.yaml` file. It shouldn't be `./internal/pkg` (with a few exceptions) should confirm to the linting rules.
